live_config_reload = true
ipc_socket = true

shell.program = "/bin/zsh"
shell.args = ["-l"]

# tmux
#shell.program = "/opt/homebrew/bin/tmux"
#shell.args = ["new", "-As", "Default"]

[window]
dimensions.columns = 120
dimensions.lines = 40

decorations = "None"
opacity = 0.8
blur = true

title = "Alacritty"
dynamic_title = false
resize_increments = true
option_as_alt = "Both"

[font]
normal = { family = "RecMonoSmCasual Nerd Font", style = "Regular" }
size = 12.5
builtin_box_drawing = true

[keyboard]
bindings = [
  # tmux
  { key = "B", mods = "Command", chars = "\u001b~" },
  { key = "T", mods = "Command", chars = "\u001b~t" },
  { key = "W", mods = "Command", chars = "\u001b~x" },
  { key = "1", mods = "Command", chars = "\u001b~1" },
  { key = "2", mods = "Command", chars = "\u001b~2" },
  { key = "3", mods = "Command", chars = "\u001b~3" },
  { key = "4", mods = "Command", chars = "\u001b~4" },
  { key = "5", mods = "Command", chars = "\u001b~5" },
  { key = "6", mods = "Command", chars = "\u001b~6" },
  { key = "7", mods = "Command", chars = "\u001b~7" },
  { key = "8", mods = "Command", chars = "\u001b~8" },
  { key = "9", mods = "Command", chars = "\u001b~9" },

  { key = "Escape", mods = "Command", action = "ToggleViMode" },
]
