export HOMEBREW_FORCE_BREWED_GIT=1
#export HOMEBREW_PIP_INDEX_URL=https://pypi.mirrors.ustc.edu.cn/simple
#export HOMEBREW_API_DOMAIN=https://mirrors.ustc.edu.cn/homebrew-bottles/api
#export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.ustc.edu.cn/homebrew-bottles
export HOMEBREW_PIP_INDEX_URL="https://mirrors.tuna.tsinghua.edu.cn/simple"
export HOMEBREW_API_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/api"
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"
eval $(/opt/homebrew/bin/brew shellenv)

export PATH=$(brew --prefix)/include:$PATH
export LIBRARY_PATH=$(brew --prefix)/lib
export VCPKG_ROOT="$HOME/.vcpkg"
export CMAKE_TOOLCHAIN_FILE="$HOME/.vcpkg/scripts/buildsystems/vcpkg.cmake"

source $(brew --prefix)/opt/fzf/shell/completion.zsh
source $(brew --prefix)/opt/fzf/shell/key-bindings.zsh
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

autoload -Uz compinit && compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*' fzf-search-display true

proxy () {
  export http_proxy="http://127.0.0.1:1080"
  export https_proxy="http://127.0.0.1:1080"
  echo "HTTP Proxy on"
}

noproxy () {
  unset http_proxy
  unset https_proxy
  echo "HTTP Proxy off"
}

icloud () {
  cd $HOME/Library/Mobile\ Documents/com\~apple\~CloudDocs
}

alias python3=/opt/homebrew/bin/python3
alias python=/opt/homebrew/bin/python3
alias pip3=/opt/homebrew/bin/pip3
alias pip=/opt/homebrew/bin/pip3
alias vi=/opt/homebrew/bin/nvim
alias vim=/opt/homebrew/bin/nvim
alias godot=/Applications/Godot.app/Contents/MacOS/Godot
alias ls="eza --icons -F"
alias tree="eza --tree"
alias cd="z"

eval "$(zoxide init zsh)"
eval "$(starship init zsh)"
