export HOMEBREW_FORCE_BREWED_GIT=1
export HOMEBREW_PIP_INDEX_URL="https://mirrors.tuna.tsinghua.edu.cn/simple"
export HOMEBREW_API_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/api"
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"
eval $(/opt/homebrew/bin/brew shellenv)

export PATH=$(brew --prefix)/include:$PATH
export LIBRARY_PATH=$(brew --prefix)/lib

export VISUAL="nvim"
export EDITOR="nvim"
export GIT_EDITOR="nvim"

autoload -U compinit; compinit
source $HOME/.zsh/fzf-tab/fzf-tab.plugin.zsh

source $(brew --prefix)/opt/fzf/shell/completion.zsh
source $(brew --prefix)/opt/fzf/shell/key-bindings.zsh
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

#autoload -Uz compinit && compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*' fzf-search-display true

proxy () {
  export http_proxy="http://127.0.0.1:7890"
  export https_proxy="http://127.0.0.1:7890"
  echo "HTTP Proxy on"
}

noproxy () {
  unset http_proxy
  unset https_proxy
  echo "HTTP Proxy off"
}

mpv_back () {
  nohup mpv ${*} >> ~/.cache/log/log.log &
}

icloud () {
  cd $HOME/Library/Mobile\ Documents/com\~apple\~CloudDocs
}

#  Move to CWD When Exiting Yazi
function y() {
  local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
  yazi "$@" --cwd-file="$tmp"
  if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
    builtin cd -- "$cwd"
  fi
  rm -f -- "$tmp"
}

# autoload ${PWD}/.env
#function chpwd() {
#  if [ -r $PWD/.env ]; then
#    source $PWD/.env
#  fi
#}

alias python3=/opt/homebrew/bin/python3
alias python=/opt/homebrew/bin/python3
alias pip3=/opt/homebrew/bin/pip3
alias pip=/opt/homebrew/bin/pip3
alias vi=/opt/homebrew/bin/nvim
alias vimdiff="/opt/homebrew/bin/nvim -d"

alias ls="eza --icons -F"
alias l="eza -l --color=auto"
alias ll="eza -l --color=auto --total-size"
alias tree="eza --tree"
alias cd="z"
alias sed=gsed

eval "$(mise activate zsh)"
eval "$(zoxide init zsh)"
eval "$(starship init zsh)"
