# homebrew
export HOMEBREW_FORCE_BREWED_GIT=1
export HOMEBREW_PIP_INDEX_URL="https://mirrors.tuna.tsinghua.edu.cn/simple"
export HOMEBREW_API_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/api"
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"
eval $(/opt/homebrew/bin/brew shellenv)

export PATH=$(brew --prefix)/include:$PATH
export LIBRARY_PATH=$(brew --prefix)/lib
export HOMEBREW=$(brew --prefix)

export VISUAL="nvim"
export EDITOR="nvim"
export GIT_EDITOR="nvim"

NEWLINE=$'\n'
PROMPT="%F{blue}%~ %#%f %F{green}%T%f${NEWLINE}"
export LESS='-Pslines %lt-%lb'

# completion
autoload -Uz compinit && compinit
zstyle ':completion:*' menu yes select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

# search history
autoload -Uz history-beginning-search-menu
zle -N history-beginning-search-menu
bindkey '^r' history-beginning-search-menu

# history with up and down
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down
bindkey "^p" up-line-or-beginning-search # Up
bindkey "^n" down-line-or-beginning-search # Down

# proxy
p () {
  export http_proxy="http://127.0.0.1:7890"
  export https_proxy="http://127.0.0.1:7890"
  echo "HTTP Proxy on"
}

np () {
  unset http_proxy
  unset https_proxy
  echo "HTTP Proxy off"
}

# mpv with nohup
mb () {
  nohup mpv ${*} >> ~/.cache/mpv_nohup.log &
}

# icloud path
icloud () {
  cd $HOME/Library/Mobile\ Documents/com\~apple\~CloudDocs
}

#  Move to CWD When Exiting Yazi
function y() {
  local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
  yazi "$@" --cwd-file="$tmp"
  if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
    builtin cd -- "$cwd"
  fi
  rm -f -- "$tmp"
}

#alias python3=/opt/homebrew/bin/python3
#alias python=/opt/homebrew/bin/python3
#alias pip3=/opt/homebrew/bin/pip3
#alias pip=/opt/homebrew/bin/pip3
alias v=/opt/homebrew/bin/nvim

alias ls="eza --icons -F"
alias l="eza -l --color=auto"
alias ll="eza -l --color=auto --total-size"
alias lg="eza --git"
alias tree="eza --tree"
alias cd="z"
alias sed=gsed
alias awk=gawk
alias grep=ggrep

eval "$(zoxide init zsh)"
