enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
start-at-login = true

after-startup-command = ['exec-and-forget brew services restart sketchybar']
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

[gaps]
inner.horizontal = 7
inner.vertical =   7
outer.left =       7
outer.bottom =     27
outer.top =        7
outer.right =      7

[mode.main.binding]
alt-leftSquareBracket = 'focus up'
alt-slash  = 'focus down'
alt-semicolon = 'focus left'
alt-quote = 'focus right'
alt-shift-leftSquareBracket = 'move up'
alt-shift-slash  = 'move down'
alt-shift-semicolon = 'move left'
alt-shift-quote = 'move right'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

cmd-h = []
cmd-alt-h = []
alt-comma = []

[mode.service.binding]
r = []
f = []
esc = []
backspace = []

alt-shift-h = []
alt-shift-j = []
alt-shift-k = []
alt-shift-l = []

[[on-window-detected]]
if.app-id = "com.baidu.netdisk"
run = "layout floating"
[[on-window-detected]]
if.app-id = "com.aone.keka"
run = "layout floating"
[[on-window-detected]]
if.app-id = "com.colliderli.iina"
run = "layout floating"
[[on-window-detected]]
if.app-id = "com.apple.QuickTimePlayerX"
run = "layout floating"
[[on-window-detected]]
if.app-id = "com.xjbeta.iina-plus"
run = "layout floating"
[[on-window-detected]]
if.app-id = "com.apple.logic10"
run = "layout floating"
[[on-window-detected]]
if.app-id = "com.blackmagic-design.DaVinciResolveLite"
run = "layout floating"
[[on-window-detected]]
if.app-id = "com.dreamtonics.svstudio.pro"
run = "layout floating"
[[on-window-detected]]
if.app-id = "org.olivevideoeditor.Olive"
run = "layout floating"
[[on-window-detected]]
if.app-id = "jp.co.celsys.CLIPSTUDIOPAINT"
run = "layout floating"
