local M = {}

M.symbol_map = {
  Array = "[]",
  Boolean = "",
  Calendar = "",
  Class = "󰠱",
  Codeium = "",
  Color = "󰏘",
  Constant = "󰏿",
  Constructor = "",
  Copilot = "",
  Enum = "",
  EnumMember = "",
  Event = "",
  Field = "󰜢",
  File = "󰈙",
  FittenCode = "",
  Folder = "󰉋",
  Function = "󰊕",
  Interface = "",
  Keyword = "󰌋",
  Method = "󰆧",
  Module = "",
  Namespace = "󰌗",
  Null = "󰟢",
  Number = "",
  Object = "󰅩",
  Operator = "󰆕",
  Package = "",
  Property = "󰜢",
  Reference = "󰈇",
  Snippet = "",
  String = "󰉿",
  Struct = "󰙅",
  TabNine = "",
  Table = "",
  Tag = "",
  Text = "󰉿",
  TypeParameter = "",
  Unit = "󰑭",
  Value = "󰎠",
  Variable = "󰀫",
  Watch = "󰥔",
}

return M
