[manager]
sort_sensitive = false
sort_reverse   = false
show_symlink   = true
ratio = [1, 4, 3]
linemode = "size_and_mtime"

[opener]
folder = [
  { run = 'open -R "$@"', desc = "Reveal in Finder" },
  { run = 'mpv "$@"', desc = "MPV" },
  { run = 'open -a kid3 "$@"', desc = "Kid3"},
  { run = '$EDITOR "$@"' },
]
archive = [
  { run = 'unar "$1"', desc = "Extract here" },
]
text = [
  { run = 'nvim "$@"', block = true },
]
image = [
  { run = 'mpv "$@"', desc = "Mpv" },
  { run = 'open "$@"', desc = "Open" },
  { run = '''exiftool "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show EXIF" },
]
video = [
  { run = 'mpv "$@"', desc = "Mpv" },
  { run = 'open "$@"', desc = "Open" },
  { run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info" },
]
audio = [
  { run = 'mpv "$@"', desc = "Mpv" },
  { run = 'open "$@"', desc = "Open" },
  { run = 'open -a kid3 "$@"', desc = "Kid3"},
  { run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info" },
]
fallback = [
  { run = 'open "$@"', desc = "Open" },
  { run = 'open -R "$@"', desc = "Reveal in Finder" },
]

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5

[log]
enabled = false
