-------------------- Hammerspoon Switcher -----------------------
--local switcher_currentSpace_onScreen = hs.window.switcher.new(hs.window.filter.new():setCurrentSpace(true), {
--  showThumbnails = false,
--  showSelectedThumbnail = true,
--  onlyActiveApplication = false,
--  textColor = { 0.9, 0.9, 0.9 },
--  highlightColor = { 0.3, 0.3, 0.3, 1 },
--  backgroundColor = { 0.5, 0.5, 0.5, 1 },
--  showTitles = false,
--  titleBackgroundColor = { 0.5, 0.5, 0.5, 1 },
--  showSelectedTitle = false,
--  closeModeBackgroundColor = { 0.5, 0.5, 0.5, 1 },
--  minimizeModeBackgroundColor = { 0.5, 0.5, 0.5, 1 },
--})
--
--hs.hotkey.bind("alt", "tab", "Next window", function()
--  switcher_currentSpace_onScreen:next()
--  hs.alert.closeAll()
--end)
--hs.hotkey.bind({ "alt", "shift" }, "tab", "Prev window", function()
--  switcher_currentSpace_onScreen:previous()
--  hs.alert.closeAll()
--end)

-------------------- Resize -----------------------
--hs.hotkey.bind({ "cmd", "ctrl" }, "o", nil, actions["Window Maximize"].run)
--hs.hotkey.bind({ "cmd", "ctrl" }, "f", nil, actions["Window Center"].run)
--hs.hotkey.bind({ "cmd", "ctrl" }, "k", nil, actions["Window Up"].run)
--hs.hotkey.bind({ "cmd", "ctrl" }, "j", nil, actions["Window Down"].run)
--hs.hotkey.bind({ "cmd", "ctrl" }, "h", nil, actions["Window Left"].run)
--hs.hotkey.bind({ "cmd", "ctrl" }, "l", nil, actions["Window Right"].run)
--hs.hotkey.bind({ "cmd", "ctrl" }, "d", nil, actions["Window Default"].run)
--hs.hotkey.bind({ "cmd", "ctrl" }, "u", nil, actions["Window Upper Left"].run)
--hs.hotkey.bind({ "cmd", "ctrl" }, "i", nil, actions["Window Upper Right"].run)
--hs.hotkey.bind({ "cmd", "ctrl" }, "n", nil, actions["Window Lower Left"].run)
--hs.hotkey.bind({ "cmd", "ctrl" }, "m", nil, actions["Window Lower Right"].run)
